version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: "package and push kube-downscaler chart to control-plane-catalogs"
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: kube-downscaler
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: capa-app-collection
          app_name: "kube-downscaler"
          app_namespace: "kube-system"
          app_collection_repo: "capa-app-collection"
          requires:
            - "package and push kube-downscaler chart to control-plane-catalogs"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: capz-app-collection
          app_name: "kube-downscaler"
          app_namespace: "kube-system"
          app_collection_repo: "capz-app-collection"
          requires:
            - "package and push kube-downscaler chart to control-plane-catalogs"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: vsphere-app-collection
          app_name: "kube-downscaler"
          app_namespace: "kube-system"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - "package and push kube-downscaler chart to control-plane-catalogs"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: cloud-director-app-collection
          app_name: "kube-downscaler"
          app_namespace: "kube-system"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - "package and push kube-downscaler chart to control-plane-catalogs"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: proxmox-app-collection
          app_name: "kube-downscaler"
          app_namespace: "kube-system"
          app_collection_repo: "proxmox-app-collection"
          requires:
            - "package and push kube-downscaler chart to control-plane-catalogs"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
